import add from './svg/add.svelte';
import archives from './svg/archives.svelte';
import arrowUp from './svg/arrow-up.svelte';
import arrowRight from './svg/arrow-right.svelte';
import ascending from './svg/ascending.svelte';
import book from './svg/book.svelte';
import bookmark from './svg/bookmark.svelte';
import calendarPlus from './svg/calendar-plus.svelte';
import chart from './svg/chart.svelte';
import checkmark from './svg/checkmark.svelte';
import chevronDown from './svg/chevron-down.svelte';
import chevronLeft from './svg/chevron-left.svelte';
import chevronRight from './svg/chevron-right.svelte';
import chevronUp from './svg/chevron-up.svelte';
import clock from './svg/clock.svelte';
import close from './svg/close.svelte';
import cometSolid from './svg/comet-solid.svelte';
import comet from './svg/comet.svelte';
import compact from './svg/compact.svelte';
import converterDown from './svg/converter-down.svelte';
import converterUp from './svg/converter-up.svelte';
import copy from './svg/copy.svelte';
import descending from './svg/descending.svelte';
import download from './svg/download.svelte';
import error from './svg/error.svelte';
import exit from './svg/exit.svelte';
import eyeHide from './svg/eye-hide.svelte';
import eyeShow from './svg/eye-show.svelte';
import feed from './svg/feed.svelte';
import feedbackCircle from './svg/feedback-circle.svelte';
import feedback from './svg/feedback.svelte';
import fileImport from './svg/file-import.svelte';
import fileUpload from './svg/file-upload.svelte';
import filter from './svg/filter.svelte';
import filterSolid from './svg/filter-solid.svelte';
import graph from './svg/graph.svelte';
import hyphen from './svg/hyphen.svelte';
import info from './svg/info.svelte';
import invertedCheckmark from './svg/inverted-checkmark.svelte';
import json from './svg/json.svelte';
import lock from './svg/lock.svelte';
import logout from './svg/logout.svelte';
import namespaceSwitcher from './svg/namespace-switcher.svelte';
import namespace from './svg/namespace.svelte';
import regions from './svg/regions.svelte';
import retention from './svg/retention.svelte';
import retry from './svg/retry.svelte';
import rocketShip from './svg/rocket-ship.svelte';
import schedules from './svg/schedules.svelte';
import search from './svg/search.svelte';
import settings from './svg/settings.svelte';
import sliders from './svg/sliders.svelte';
import spinner from './svg/spinner.svelte';
import spinnerSolid from './svg/spinner-solid.svelte';
import starEmpty from './svg/star-empty.svelte';
import starFilled from './svg/star-filled.svelte';
import terminal from './svg/terminal.svelte';
import trash from './svg/trash.svelte';
import tutorial from './svg/tutorial.svelte';
import upload from './svg/upload.svelte';
import usage from './svg/usage.svelte';
import verticalEllipsis from './svg/vertical-ellipsis.svelte';
import warning from './svg/warning.svelte';
import workflow from './svg/workflow.svelte';
export declare type IconName = keyof typeof icons;
export declare const icons: {
    add: typeof add;
    archives: typeof archives;
    'arrow-up': typeof arrowUp;
    'arrow-right': typeof arrowRight;
    ascending: typeof ascending;
    book: typeof book;
    bookmark: typeof bookmark;
    'calendar-plus': typeof calendarPlus;
    chart: typeof chart;
    checkmark: typeof checkmark;
    'chevron-down': typeof chevronDown;
    'chevron-left': typeof chevronLeft;
    'chevron-right': typeof chevronRight;
    'chevron-up': typeof chevronUp;
    clock: typeof clock;
    close: typeof close;
    'comet-solid': typeof cometSolid;
    comet: typeof comet;
    compact: typeof compact;
    'converter-down': typeof converterDown;
    'converter-up': typeof converterUp;
    copy: typeof copy;
    descending: typeof descending;
    download: typeof download;
    error: typeof error;
    exit: typeof exit;
    'eye-hide': typeof eyeHide;
    'eye-show': typeof eyeShow;
    feed: typeof feed;
    'feedback-circle': typeof feedbackCircle;
    feedback: typeof feedback;
    'file-import': typeof fileImport;
    'file-upload': typeof fileUpload;
    filter: typeof filter;
    'filter-solid': typeof filterSolid;
    graph: typeof graph;
    hyphen: typeof hyphen;
    info: typeof info;
    'inverted-checkmark': typeof invertedCheckmark;
    json: typeof json;
    lock: typeof lock;
    logout: typeof logout;
    'namespace-switcher': typeof namespaceSwitcher;
    namespace: typeof namespace;
    regions: typeof regions;
    retention: typeof retention;
    retry: typeof retry;
    'rocket-ship': typeof rocketShip;
    schedules: typeof schedules;
    search: typeof search;
    settings: typeof settings;
    sliders: typeof sliders;
    spinner: typeof spinner;
    'star-empty': typeof starEmpty;
    'star-filled': typeof starFilled;
    'spinner-solid': typeof spinnerSolid;
    terminal: typeof terminal;
    trash: typeof trash;
    tutorial: typeof tutorial;
    upload: typeof upload;
    usage: typeof usage;
    'vertical-ellipsis': typeof verticalEllipsis;
    warning: typeof warning;
    workflow: typeof workflow;
};
